/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package seungkyu.msa.service.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum PaymentOrderStatus implements org.apache.avro.generic.GenericEnumSymbol<PaymentOrderStatus> {
  PENDING, CANCELLED, CANCELLING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentOrderStatus\",\"namespace\":\"seungkyu.msa.service.kafka.model\",\"symbols\":[\"PENDING\",\"CANCELLED\",\"CANCELLING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
