/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package seungkyu.msa.service.kafka.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RestaurantApprovalResponseAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5719506627103231634L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RestaurantApprovalResponseAvroModel\",\"namespace\":\"seungkyu.msa.service.kafka.model\",\"fields\":[{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"restaurantId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"orderApprovalStatus\",\"type\":{\"type\":\"enum\",\"name\":\"OrderApprovalStatus\",\"symbols\":[\"APPROVED\",\"REJECTED\"]}},{\"name\":\"createdAt\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RestaurantApprovalResponseAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RestaurantApprovalResponseAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RestaurantApprovalResponseAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RestaurantApprovalResponseAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RestaurantApprovalResponseAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RestaurantApprovalResponseAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RestaurantApprovalResponseAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RestaurantApprovalResponseAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RestaurantApprovalResponseAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String orderId;
  private java.lang.String restaurantId;
  private seungkyu.msa.service.kafka.model.OrderApprovalStatus orderApprovalStatus;
  private long createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RestaurantApprovalResponseAvroModel() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param restaurantId The new value for restaurantId
   * @param orderApprovalStatus The new value for orderApprovalStatus
   * @param createdAt The new value for createdAt
   */
  public RestaurantApprovalResponseAvroModel(java.lang.String orderId, java.lang.String restaurantId, seungkyu.msa.service.kafka.model.OrderApprovalStatus orderApprovalStatus, java.lang.Long createdAt) {
    this.orderId = orderId;
    this.restaurantId = restaurantId;
    this.orderApprovalStatus = orderApprovalStatus;
    this.createdAt = createdAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return restaurantId;
    case 2: return orderApprovalStatus;
    case 3: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = value$ != null ? value$.toString() : null; break;
    case 1: restaurantId = value$ != null ? value$.toString() : null; break;
    case 2: orderApprovalStatus = (seungkyu.msa.service.kafka.model.OrderApprovalStatus)value$; break;
    case 3: createdAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.String getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'restaurantId' field.
   * @return The value of the 'restaurantId' field.
   */
  public java.lang.String getRestaurantId() {
    return restaurantId;
  }


  /**
   * Sets the value of the 'restaurantId' field.
   * @param value the value to set.
   */
  public void setRestaurantId(java.lang.String value) {
    this.restaurantId = value;
  }

  /**
   * Gets the value of the 'orderApprovalStatus' field.
   * @return The value of the 'orderApprovalStatus' field.
   */
  public seungkyu.msa.service.kafka.model.OrderApprovalStatus getOrderApprovalStatus() {
    return orderApprovalStatus;
  }


  /**
   * Sets the value of the 'orderApprovalStatus' field.
   * @param value the value to set.
   */
  public void setOrderApprovalStatus(seungkyu.msa.service.kafka.model.OrderApprovalStatus value) {
    this.orderApprovalStatus = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.createdAt = value;
  }

  /**
   * Creates a new RestaurantApprovalResponseAvroModel RecordBuilder.
   * @return A new RestaurantApprovalResponseAvroModel RecordBuilder
   */
  public static seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder newBuilder() {
    return new seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder();
  }

  /**
   * Creates a new RestaurantApprovalResponseAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RestaurantApprovalResponseAvroModel RecordBuilder
   */
  public static seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder newBuilder(seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder other) {
    if (other == null) {
      return new seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder();
    } else {
      return new seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new RestaurantApprovalResponseAvroModel RecordBuilder by copying an existing RestaurantApprovalResponseAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new RestaurantApprovalResponseAvroModel RecordBuilder
   */
  public static seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder newBuilder(seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel other) {
    if (other == null) {
      return new seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder();
    } else {
      return new seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for RestaurantApprovalResponseAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RestaurantApprovalResponseAvroModel>
    implements org.apache.avro.data.RecordBuilder<RestaurantApprovalResponseAvroModel> {

    private java.lang.String orderId;
    private java.lang.String restaurantId;
    private seungkyu.msa.service.kafka.model.OrderApprovalStatus orderApprovalStatus;
    private long createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[1].schema(), other.restaurantId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orderApprovalStatus)) {
        this.orderApprovalStatus = data().deepCopy(fields()[2].schema(), other.orderApprovalStatus);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[3].schema(), other.createdAt);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing RestaurantApprovalResponseAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.restaurantId)) {
        this.restaurantId = data().deepCopy(fields()[1].schema(), other.restaurantId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderApprovalStatus)) {
        this.orderApprovalStatus = data().deepCopy(fields()[2].schema(), other.orderApprovalStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[3].schema(), other.createdAt);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder setOrderId(java.lang.String value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'restaurantId' field.
      * @return The value.
      */
    public java.lang.String getRestaurantId() {
      return restaurantId;
    }


    /**
      * Sets the value of the 'restaurantId' field.
      * @param value The value of 'restaurantId'.
      * @return This builder.
      */
    public seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder setRestaurantId(java.lang.String value) {
      validate(fields()[1], value);
      this.restaurantId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'restaurantId' field has been set.
      * @return True if the 'restaurantId' field has been set, false otherwise.
      */
    public boolean hasRestaurantId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'restaurantId' field.
      * @return This builder.
      */
    public seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder clearRestaurantId() {
      restaurantId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderApprovalStatus' field.
      * @return The value.
      */
    public seungkyu.msa.service.kafka.model.OrderApprovalStatus getOrderApprovalStatus() {
      return orderApprovalStatus;
    }


    /**
      * Sets the value of the 'orderApprovalStatus' field.
      * @param value The value of 'orderApprovalStatus'.
      * @return This builder.
      */
    public seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder setOrderApprovalStatus(seungkyu.msa.service.kafka.model.OrderApprovalStatus value) {
      validate(fields()[2], value);
      this.orderApprovalStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderApprovalStatus' field has been set.
      * @return True if the 'orderApprovalStatus' field has been set, false otherwise.
      */
    public boolean hasOrderApprovalStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderApprovalStatus' field.
      * @return This builder.
      */
    public seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder clearOrderApprovalStatus() {
      orderApprovalStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder setCreatedAt(long value) {
      validate(fields()[3], value);
      this.createdAt = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public seungkyu.msa.service.kafka.model.RestaurantApprovalResponseAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RestaurantApprovalResponseAvroModel build() {
      try {
        RestaurantApprovalResponseAvroModel record = new RestaurantApprovalResponseAvroModel();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.String) defaultValue(fields()[0]);
        record.restaurantId = fieldSetFlags()[1] ? this.restaurantId : (java.lang.String) defaultValue(fields()[1]);
        record.orderApprovalStatus = fieldSetFlags()[2] ? this.orderApprovalStatus : (seungkyu.msa.service.kafka.model.OrderApprovalStatus) defaultValue(fields()[2]);
        record.createdAt = fieldSetFlags()[3] ? this.createdAt : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RestaurantApprovalResponseAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<RestaurantApprovalResponseAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RestaurantApprovalResponseAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<RestaurantApprovalResponseAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orderId);

    out.writeString(this.restaurantId);

    out.writeEnum(this.orderApprovalStatus.ordinal());

    out.writeLong(this.createdAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString();

      this.restaurantId = in.readString();

      this.orderApprovalStatus = seungkyu.msa.service.kafka.model.OrderApprovalStatus.values()[in.readEnum()];

      this.createdAt = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readString();
          break;

        case 1:
          this.restaurantId = in.readString();
          break;

        case 2:
          this.orderApprovalStatus = seungkyu.msa.service.kafka.model.OrderApprovalStatus.values()[in.readEnum()];
          break;

        case 3:
          this.createdAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










